name: pitakaguide
description: Pitaka Guide

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  shared_preferences: ^2.0.14
  substring_highlight: ^1.0.33
  fast_csv: ^0.1.38
  app_popup_menu: ^1.0.0
  flutter_slidable: ^1.2.0
  vs_scrollbar: ^0.2.1
  draggable_scrollbar: ^0.1.0
  toggle_switch: ^1.3.0
  community_material_icon: ^5.9.55
  native_pdf_renderer: ^4.0.1
  # pdfx: ^2.0.1+2
  equatable: ^2.0.3
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  flutter_widget_from_html_core: ^0.8.4
  # path_provider: ^2.0.8
  # path: ^1.8.0
  # equatable: ^2.0.3

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_lints:
  build_runner: ^2.1.10
  icons_launcher: ^1.1.7
  flutter_native_splash: ^2.0.2
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/books/
    - assets/books/pdf/
    - assets/books/cover/
    - assets/info.html

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/pitaka_guide.png"

flutter_native_splash:
  color: "#a73800"
  image: "assets/icon/pitaka_guide_circle.png"

